server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"
      - "application_stage.yml"
  profiles:
    active:
      - "prod"


build:
  version: "V 1.0"
app:
  name: "accounts-microservice"

accounts:
  message: "Welcome to Accounts related local(Dev) Api's"
  contactDetails:
    name: "Ashish"
    email: "ashish1234@bcards.com"
  onCallSupport:
    - "+91-1234567890"
    - "+91-1234567899"
