
#The below line tells the value with which this profile will get activated
spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "V 3.0 PROD env"

accounts:
  message: "Welcome to Accounts related PROD env Api's"
  contactDetails:
    name: "Avigyan Mohanty - PROD Lead"
    email: "avigyanMohanty1234@bcards.com"
  onCallSupport:
    - "+91-1234567893"
    - "+91-1234567894"
