spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to loans related prod ENV APIs "
  contactDetails:
    name: "Rinku Singh - Product Owner"
    email: "singhrinkuind@bcards.com"
  onCallSupport:
    - "+91-1123456789"
    - "+91-1223456789"