
#The below line tells the value with which this profile will get activated
spring:
  config:
    activate:
      on-profile: "stage"

build:
  version: "V 2.5 Stage env"

accounts:
  message: "Welcome to Accounts related to Staging env Api's"
  contactDetails:
    name: "Siddhartha Mishra - Staging env Lead"
    email: "sidned12345@bcards.com"
  onCallSupport:
    - "+91-1234567893"
    - "+91-1234567894"
