services:

  configserver:
    image: "captainashish/configserver:s6"
    container_name: "configserver-microservice"
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microdemo


  accounts:
    image: "captainashish/accounts:s6"
    container_name: accounts-microservice
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microdemo
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default

  loans:
    image: "captainashish/loans:s6"
    container_name: loans-microservice
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microdemo
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default


  cards:
    image: "captainashish/cards:s6"
    container_name: cards-microservice
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microdemo
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default



networks:
  microdemo:
    driver: "bridge"