spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 2000
            response-timeout: 5s
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: UNRESTRICTED
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "micro demo gateway server"
    version: "1.0.0"


logging:
  level:
    com:
      micro:
        gatewayserver: DEBUG


resilience4j:
  circuitbreaker:
    instances:
      accountsServiceCircuitBreaker:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
