
build:
  version: "V 1.0"
app:
  name: "accounts-microservice"

accounts:
  message: "Welcome to Accounts related local(Dev) Api's"
  contactDetails:
    name: "Ashish"
    email: "ashish1234@bcards.com"
  onCallSupport:
    - "+91-1234567890"
    - "+91-1234567899"
