
build:
  version: "3.0"
app:
  name: "Cards microservice"

cards:
  message: "Welcome to cards related local(dev) APIs "
  contactDetails:
    name: "MS DHONI - Developer"
    email: "msdhoni7thala@bcards.com"
  onCallSupport:
    - "+91-1234567890"
    - "+91-1234567899"
