build:
  version: "2.0"

cards:
  message: "Welcome to cards related QA ENV APIs "
  contactDetails:
    name: "Suresh Raina - QA Lead"
    email: "sureshrainaog@bcards.com"
  onCallSupport:
    - "+91-1234455660"
    - "+91-1234455669"