apiVersion: 1


deleteDataSources:
  - name: Prometheus
  - name: Loki

dataSources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET


  - name: Loki
    type: loki
    uid: loki
    url: http://gateway:3100
    access: proxy
    orgId: 1
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgId"
    secureJsonData:
      httpHeaderValue1: "tenant1"
